### PR TITLE
Update Node Version to Resolve Build Errors for @typescript-eslint/parser and @typescript-eslint/eslint-plugin

### PR DESCRIPTION
**Pull request by Fritsch-Tech**
#### 🔧 Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Codebase improvement
- [ ] Other (if none of the other choices apply)

#### 🚨 Checklist

- [x] I've read the [guidelines for contributing](https://github.com/gremo/react-directus/blob/main/CONTRIBUTING.md)
- [x] I've added necessary documentation (if appropriate)
- [x] I've ensured that my code additions do not fail linting or unit tests (if applicable)
#### Description

This pull request updates the Node version to address build errors related to `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` version 6.2.0.

The recent version `6.2.0` of `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` introduced a breaking change, which caused build errors in the previous Node version. Updating Node to the latest version resolves these build errors and ensures compatibility with the latest dependencies.

For reference, the breaking change in `@typescript-eslint/parser` version 6.2.0 can be found in the following link: [typescript-eslint/typescript-eslint - Changelog](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/CHANGELOG.md#600-2023-07-10).

This update ensures that the project's codebase is up-to-date and builds without any issues with the latest TypeScript ESLint dependencies.

### CODE REVIEW

**Comment by gremo** [comment]
This would solve issues in the dev container (btw, we could put node:lts as alternative). But it won't solve the test workflow, so also https://github.com/gremo/react-directus/blob/main/.github/workflows/test.yaml#L30 should be changed, to.. which version? 18? WDYT?

**Comment by Fritsch-Tech** [comment]
I would use version 18, this would give us 2 more years.
We could also test it with version 20 and see if it causes any issues. If not it might be better to upgrade rightaway.

(Node Releases)[https://nodejs.dev/en/about/releases/]

**Comment by gremo** [comment]
Go for lts for both (I don't know if github actions supports lts)

**Comment by Fritsch-Tech** [comment]
Not sure, but i just used lts-hydrogeb bzw. lts/hydrogen as described in [setup-node](https://github.com/actions/setup-node)

**Comment by gremo** [comment]
Ok I'm gonna close this because I messed up with the PR editing it 😄 I've already pushed the change, let renovate do the job of updating the dependecies 💪

**Comment by gremo** [comment]
Well it seems not solving the test error...

**Comment by Fritsch-Tech** [comment]
This could be the issue (https://github.com/microsoft/TypeScript/issues/37991)

Currently the target in the .tsconfig is ES5, is there any reson not to update it to ES6?

I tried it localy and i got no errors.

**Comment by gremo** [comment]
Well I think we can move to ES6. Maybe I've chosen ES5 when I created this package.

I suppose that React won't suppoort any non-ES6 browser, right? I mean React 16 that is the minimum version this package support.

**Comment by Fritsch-Tech** [comment]
Not really. If someone truly needs ES5 support, they will use Babel to convert ES6 to ES5 anyway.

**Comment by gremo** [comment]
Still not working using ES6 at least in gha 🙈

**Pull request closed without merging**
